### ISSUE TITLE
藏剑问题

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/macro#15]
## publish

在macro和bps中的发布里，心法的列表，隐藏一下重剑。

**Comment by iRuxu** [comment]
## macro和bps
侧边栏，默认隐藏重剑

**Comment by iRuxu** [comment]
## 数据库
批量替换重剑攻略和宏为轻剑

**Comment by Kaviilee** [comment]
@iRuxu 剩下数据库没有进行批量操作
