### ISSUE TITLE
宏库-配装方案

### ISSUE THREAD

**Issue by M-ls** [JX3BOX/macro#17]
![image](https://user-images.githubusercontent.com/36070993/216754479-9e11cb0d-e57c-48bf-a0e1-772010bf8515.png)
点击此链接会在当前链接打开配装界面
从而导致废弃之前的编辑界面
需求新页面打开/提示是否保存当前编辑/自动存储为草稿（并提示用户已保存草稿）

**Comment by M-ls** [comment]
![image](https://user-images.githubusercontent.com/36070993/216754639-efd498fe-5335-4537-8ffb-e1dd5a64736e.png)
编辑界面
![image](https://user-images.githubusercontent.com/36070993/216754648-2ec4e0ca-122b-4b4c-b7f4-24e3f4cdaf56.png)
发布后二次编辑界面
能否显示一致？

**Comment by iRuxu** [comment]
> ![image](https://user-images.githubusercontent.com/36070993/216754479-9e11cb0d-e57c-48bf-a0e1-772010bf8515.png) 点击此链接会在当前链接打开配装界面 从而导致废弃之前的编辑界面 需求新页面打开/提示是否保存当前编辑/自动存储为草稿（并提示用户已保存草稿）

已改为新窗打开

**Comment by iRuxu** [comment]
> ![image](https://user-images.githubusercontent.com/36070993/216754639-efd498fe-5335-4537-8ffb-e1dd5a64736e.png) 编辑界面 ![image](https://user-images.githubusercontent.com/36070993/216754648-2ec4e0ca-122b-4b4c-b7f4-24e3f4cdaf56.png) 发布后二次编辑界面 能否显示一致？

醉栩处理

**Comment by iRuxu** [comment]
![Uploading image.png…]()

**Comment by iRuxu** [comment]
## 宏编辑
可能接口需要添加支持ids?=xxx  

关联的配装，要显示名字

- [x] 已完成

**Comment by iRuxu** [comment]
## 发布中心
在publish库，完成上述后

另外把用户自定义头条隐藏掉！不然他们总是有作者乱去掉。不要引那个模块即可

- [x] 已完成
