### ISSUE TITLE
模拟器与宏编辑器迁移

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/macro#19]
## 背景
在本次3.0的调整中，要合并掉一些项目
同一个挂靠的项目，除了是足够强大的应用（比如配装器）都合并到对应的项目下做成多页面模式，其它小应用都要合并掉
方便我们迭代项目
全站在此次中，同时全部会做成history模式，以优化seo
以及本次暂时虽然保留还是vue2，但是在下次4.0的时候就会升级到vue3.0或者vue4，所以一些能用原生的方法就要用原生（比如复制功能），已经被vue2移除的功能也同时要检查去掉

- [x] 已完成

**Comment by iRuxu** [comment]
## 宏编辑器
当前线上东西：https://www.jx3box.com/app/macroeditor/
路由为/macro/macroeditor，迁移app库下对应功能过来。
旧的路由跳转到这个新路由来。（涉及macro作侧边栏nav.vue、app库跳转与app.vue、头部菜单、box矩阵、发布中心macro页面中的修改）

- [x] 已完成

**Comment by iRuxu** [comment]
## 奇穴模拟器
当前线上东西：https://www.jx3box.com/app/talent/
路由为/macro/talent，迁移app库下对应功能过来。
旧的路由跳转到这个新路由来。（涉及macro作侧边栏nav.vue、app库跳转与app.vue、box矩阵、发布中心macro页面中的修改）

- [x] 已完成

**Comment by iRuxu** [comment]
## 镇派模拟器
当前线上东西：https://www.jx3box.com/app/talent2
路由为/macro/talent2，迁移app库下对应功能过来。
旧的路由跳转到这个新路由来。（涉及macro作侧边栏nav.vue、app库跳转与app.vue、box矩阵、发布中心macro页面中的修改）

- [x] 已完成

**Comment by iRuxu** [comment]
## 4.0预备工作
1. 移除所有复制组件，或强vue2组件，改成原生形式。
2. 移除所有filter和vue2的在3中被废弃的特性

- [x] 已完成

**Comment by iRuxu** [comment]
## 经脉模拟器
通你妹，同上

- [x] 已完成

**Comment by iRuxu** [comment]
## 宏页面优化
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/8476969/217959181-7a0a7cd1-0fb3-41ab-98d5-51bf9c05dc03.png">

现在切换tab，虽然切换路由，但是因为现在的路由是会让整个页面都跟着变（所以公共头和侧边栏啥的会闪动）
这系列tab帮我用一个公用的包一层，
同时列表区域组件抽离出去，接口请求后，格式化一样的格式传进去

- [x] 已完成

**Comment by Kaviilee** [comment]
## 宏收藏夹
筛选不生效 /api/cms/posts/user/my/fav?type=macro&per=10&page=1&order=update&client=std

**Comment by iRuxu** [comment]
## 布局优化
<img width="230" alt="image" src="https://user-images.githubusercontent.com/8476969/218335877-616faff9-4053-4d91-b1e2-83f917ebffde.png">

列表页，统一用List，包含相同左右侧边栏+顶部的tab区域。

单页，用Single，固定包含一个作者信息的左侧边栏，可一个可slot的右侧边栏。（后面其他栏目可能有类似的场景，都抄这个项目）

应用，都使用只有头部和底部的  AppLayout（要支持bread信息的传入）

- [x] 已完成

**Comment by iRuxu** [comment]
> posts/user/my/fav

<img width="1343" alt="image" src="https://user-images.githubusercontent.com/8476969/218336426-dc09e832-7586-43c5-afc6-d4ec203d96be.png">

由于没有普适性（其它栏目无类似逻辑），同时简单的继承传递不行，因为还存在分页匹配一致等问题。
调整为【宏收藏夹】和【亲友的宏】直接整个筛选栏全部不要。

- [ ] 已完成

**Comment by iRuxu** [comment]
> ## 宏收藏夹
> 筛选不生效 /api/cms/posts/user/my/fav?type=macro&per=10&page=1&order=update&client=std

<img width="1343" alt="image" src="https://user-images.githubusercontent.com/8476969/218336426-dc09e832-7586-43c5-afc6-d4ec203d96be.png">

由于没有普适性（其它栏目无类似逻辑），同时简单的继承传递不行，因为还存在分页匹配一致等问题。
调整为【宏收藏夹】和【亲友的宏】直接整个筛选栏全部不要。

- [x] 已完成

**Comment by iRuxu** [comment]
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/8476969/218344587-d5b61831-763e-43cb-8dd4-87dcf13a87db.png">

作者问题
- [x] 已完成

**Comment by iRuxu** [comment]
## 布局优化
AppLayout 加入bread组件，增加slug 之类的参数
如果bread没有传入icon时，默认应该就用getIcon(slug)去显示图片（如果不是此逻辑，就优化common-ui）
应用中直接用AppLayout传入slug等，去掉多套的div#app

- [x] 已完成
