### ISSUE TITLE
talent存在bug

### ISSUE THREAD

**Issue by M-ls** [JX3BOX/macro#23]
1.保存预设方案时应根据talent/talent2类型对应传std/origin，而不是client选择，实际表现有点奇怪：
talent，client应为origin，实为origin
![image](https://github.com/JX3BOX/macro/assets/36070993/b1ff8ac1-c1c0-4d1e-aba5-807a0f1ee14b)
talent2，client应为std，实为origin
![image](https://github.com/JX3BOX/macro/assets/36070993/019c4441-0a72-4a15-b5fc-c5121e06c6ec)

点开“我的预设"时读取已保存的talent列表【https://cms.jx3box.com/api/cms/app/talents?client=std&type=talent2&page=1&per=10 】请求传了客户端参数，根据测试发现在不传client时talent2默认返回了origin
应根据talent/talent类型返回std/origin或让cms返回全部client

2.talent2解析，除丐帮全部报错

**Comment by iRuxu** [comment]
<img width="809" alt="image" src="https://github.com/JX3BOX/macro/assets/8476969/ac6ca010-550c-4d43-9378-cccc44c4b50e">

武学研习的指定版本未生效

- [x] 已完成

**Comment by iRuxu** [comment]
<img width="1111" alt="image" src="https://github.com/JX3BOX/macro/assets/8476969/b28d9730-9115-4aaf-ae00-d8baffeb61d8">

- [x] 已完成
